# Generated by Django 3.0.6 on 2020-06-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationHR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='positionId',
            new_name='position',
        ),
    ]
