# Generated by Django 3.0.6 on 2020-06-05 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationHR', '0002_auto_20200605_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('assessment', models.CharField(max_length=250)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=18)),
                ('salary', models.IntegerField(default=0)),
                ('workedFor', models.CharField(max_length=255)),
                ('recieved', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0.0)),
                ('scoreBefore', models.FloatField(default=0.0)),
                ('scoreAfter', models.FloatField(default=0.0)),
                ('starred', models.BooleanField(default=False)),
                ('cardId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicationHR.Cards')),
            ],
        ),
    ]
