# Generated by Django 3.0.6 on 2020-06-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationHR', '0003_employees_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
