# Generated by Django 3.0.6 on 2020-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationHR', '0004_auto_20200605_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertoken',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='token'),
        ),
    ]
