# Generated by Django 3.0.6 on 2020-06-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationHR', '0005_user_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='cardId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='applicationHR.Cards'),
        ),
    ]
